"""
Phase 2: State Interceptor Middleware (02_state_interceptor.py)
Non-invasive state interception hooks for AutoAgent trajectories.
"""

import os
import json
import time
import hashlib
from typing import List, Optional, Dict, Any, Callable, Set
from queue import Queue
from pydantic import BaseModel, Field

class AgentStageState(BaseModel):
    """
    Pydantic representation of an intermediate agentic reasoning stage.
    """
    trajectory_id: str = Field(..., description="Unique UUID for the end-to-end task run")
    stage_id: int = Field(..., description="1-indexed sequence stage (1 to 5)")
    agent_name: str = Field(..., description="Active agent (e.g. Orchestrator, LocalFileAgent)")
    action_type: str = Field(..., description="Action executed (e.g., retrieval, reasoning, python_exec)")
    input_context: str = Field(..., description="Input context c_{i-1} received by the stage")
    stage_output: str = Field(..., description="Output text c_i generated by the stage")
    retrieved_evidence: Optional[List[str]] = Field(default=None, description="External evidence chunks")
    token_logprobs: Optional[List[float]] = Field(default=None, description="Token-level log-probabilities")
    confidence_score: Optional[float] = Field(default=None, description="Calibrated confidence p_i")
    parent_stage_ids: List[int] = Field(default_factory=list, description="IDs of preceding stages consumed")
    timestamp: float = Field(default_factory=time.time)

    def compute_hash(self) -> str:
        """Returns SHA256 of the stage output for deduplication and loop detection."""
        return hashlib.sha256(self.stage_output.encode("utf-8")).hexdigest()

    def to_log_dict(self) -> Dict[str, Any]:
        """Serializes state for JSONL logging."""
        return self.model_dump()


import threading
from concurrent.futures import ThreadPoolExecutor

class StateInterceptor:
    """
    Thread-safe interceptor capturing inter-agent state transitions in real time
    with non-blocking asynchronous verification and speculative execution support.
    """
    def __init__(self, log_dir: str = "/content/drive/MyDrive/Capstone_Project/logs"):
        self.log_dir = log_dir if os.path.exists("/content/drive") else "./Capstone_Project/logs"
        os.makedirs(self.log_dir, exist_ok=True)
        self.log_file = os.path.join(self.log_dir, "trajectories.jsonl")
        self.state_queue: Queue = Queue()
        self.active_trajectories: Dict[str, List[AgentStageState]] = {}
        self.abort_events: Dict[str, threading.Event] = {}
        self.verification_results: Dict[str, Dict[int, Any]] = {}
        self.position_matrices: Dict[str, Dict[int, Set[int]]] = {}  # Trajectory -> Child Stage -> Parent Stages
        self.worker_thread: Optional[threading.Thread] = None
        self.detector = None
        self.on_cascade_callback: Optional[Callable] = None
        self.running: bool = False

    def start_async_worker(self, detector, on_cascade_callback: Optional[Callable] = None):
        """
        Starts a non-blocking daemon thread that verifies states in parallel with agent execution.
        """
        self.detector = detector
        self.on_cascade_callback = on_cascade_callback
        self.running = True
        self.worker_thread = threading.Thread(target=self._worker_loop, daemon=True)
        self.worker_thread.start()
        print("[*] StateInterceptor: Asynchronous Parallel Verification Engine started.")

    def stop_async_worker(self):
        """Terminates the asynchronous verification loop."""
        self.running = False
        if self.worker_thread is not None:
            self.state_queue.put(None)  # Sentinel to unblock queue.get()
            self.worker_thread.join(timeout=1.0)
            print("[*] StateInterceptor: Asynchronous Worker safely terminated.")

    def _worker_loop(self):
        """Background thread executing CHARM verification while downstream agents execute."""
        while self.running:
            item = self.state_queue.get()
            if item is None:
                break

            state: AgentStageState = item
            tid = state.trajectory_id
            sid = state.stage_id

            if tid not in self.verification_results:
                self.verification_results[tid] = {}

            if self.detector is not None:
                t0 = time.time()
                res = self.detector.evaluate_stage(
                    stage_id=sid,
                    current_output=state.stage_output,
                    prior_context=state.input_context,
                    retrieved_evidence=state.retrieved_evidence or [],
                    confidence_score=state.confidence_score
                )
                lat_ms = (time.time() - t0) * 1000.0
                res["async_eval_latency_ms"] = round(lat_ms, 2)
                self.verification_results[tid][sid] = res

                # Check if cascade triggered
                if res.get("cascade_flag", False):
                    print(f"[!] ASYNC ALERT: Cascade detected in Trajectory {tid[:8]} at Step {sid} (p={res.get('p_cascade')})!")
                    if tid in self.abort_events:
                        self.abort_events[tid].set()

                    if self.on_cascade_callback is not None:
                        try:
                            self.on_cascade_callback(res, state)
                        except Exception as cb_err:
                            print(f"[!] Error in async cascade callback: {cb_err}")

            self.state_queue.task_done()

    def is_trajectory_aborted(self, trajectory_id: str) -> bool:
        """Returns True if an asynchronous interrupt was triggered for this trajectory."""
        evt = self.abort_events.get(trajectory_id)
        return evt.is_set() if evt is not None else False

    def wait_for_verification(self, trajectory_id: str, stage_id: int, timeout: float = 0.60) -> Optional[Dict[str, Any]]:
        """
        Polls until the background CHARM worker finishes verifying stage_id or timeout expires.
        """
        start_time = time.time()
        while time.time() - start_time < timeout:
            if self.is_trajectory_aborted(trajectory_id):
                return {"cascade_flag": True, "p_cascade": 1.0}
            if trajectory_id in self.verification_results:
                if stage_id in self.verification_results[trajectory_id]:
                    return self.verification_results[trajectory_id][stage_id]
            time.sleep(0.02)
        return self.verification_results.get(trajectory_id, {}).get(stage_id)

    def execute_gated_action(
        self,
        trajectory_id: str,
        prior_stage_id: int,
        action_func: Callable,
        *args,
        **kwargs
    ) -> Any:
        """
        Two-Phase Commit (2PC) Action Gate:
        Guarantees that dangerous/irreversible operations (payments, DB mutations, file writes)
        are BLOCKED until CHARM finishes verifying the preceding stage.
        If an anomaly is detected, the operation is completely halted.
        """
        if self.is_trajectory_aborted(trajectory_id):
            raise PermissionError(
                f"[!] SAFETY LOCK TRIGGERED: Dangerous action aborted in Trajectory {trajectory_id[:8]} "
                f"because a prior reasoning step was flagged as a cascading hallucination."
            )

        # Wait for the background CHARM worker to certify the prior stage
        res = self.wait_for_verification(trajectory_id, prior_stage_id, timeout=0.60)

        # If flagged or timed out with abort event set, block execution
        if self.is_trajectory_aborted(trajectory_id) or (res and res.get("cascade_flag", False)):
            raise PermissionError(
                f"[!] SAFETY LOCK TRIGGERED: Preceding Stage {prior_stage_id} failed verification "
                f"(p_cascade={res.get('p_cascade') if res else 'Unknown'}). Dangerous action prevented."
            )

        print(f"[*] SAFETY GATE PASSED: Stage {prior_stage_id} certified clean. Executing action.")
        return action_func(*args, **kwargs)

    def rollback_and_resume_async(
        self,
        trajectory_id: str,
        rollback_target_stage: int,
        corrected_output: str,
        corrected_evidence: Optional[List[str]] = None,
        agent_name: str = "RollbackRecoveryAgent"
    ) -> AgentStageState:
        """
        Rollback Recovery Lifecycle:
        1. Truncates corrupted downstream states back to (rollback_target_stage - 1).
        2. Clears the trajectory abort flag.
        3. Injects the corrected premise into the timeline.
        4. Re-engages the asynchronous background queue for subsequent stages.
        """
        print(f"[*] RECOVERY: Rolling back Trajectory {trajectory_id[:8]} to Step {rollback_target_stage}...")
        
        # 1. Truncate active trajectory history to clean prefix
        if trajectory_id in self.active_trajectories:
            clean_history = [s for s in self.active_trajectories[trajectory_id] if s.stage_id < rollback_target_stage]
            self.active_trajectories[trajectory_id] = clean_history

        # 2. Clear verification cache for corrupted stages
        if trajectory_id in self.verification_results:
            self.verification_results[trajectory_id] = {
                sid: res for sid, res in self.verification_results[trajectory_id].items()
                if sid < rollback_target_stage
            }

        # 3. Clear the abort event so pipeline can execute again
        if trajectory_id in self.abort_events:
            self.abort_events[trajectory_id].clear()

        # 4. Get preceding context from the last valid stage
        prior_state = self.active_trajectories[trajectory_id][-1] if self.active_trajectories.get(trajectory_id) else None
        prior_context = prior_state.stage_output if prior_state else "Cleaned Root Context"

        # 5. Capture the corrected stage (automatically enqueued to async worker)
        corrected_state = self.capture_stage(
            trajectory_id=trajectory_id,
            stage_id=rollback_target_stage,
            agent_name=agent_name,
            action_type="remediated_step",
            input_context=prior_context,
            stage_output=corrected_output,
            retrieved_evidence=corrected_evidence or (prior_state.retrieved_evidence if prior_state else [])
        )

        print(f"[+] RECOVERY COMPLETE: Corrected state injected at Step {rollback_target_stage}. Asynchronous parallel guardrail resumed.")
        return corrected_state

    def register_causal_dependency(self, trajectory_id: str, child_stage_id: int, parent_stage_ids: List[int]):
        """
        Populates the Positional Causal Dependency Matrix M[i, j] = 1.
        Records which preceding stages child_stage_id explicitly relied on.
        """
        if trajectory_id not in self.position_matrices:
            self.position_matrices[trajectory_id] = {}
        self.position_matrices[trajectory_id][child_stage_id] = set(parent_stage_ids)

    def get_tainted_subgraph(self, trajectory_id: str, root_cause_stage: int) -> Set[int]:
        """
        Computes the transitive closure of corrupted stages using the Positional Matrix.
        Finds all downstream stages that directly or indirectly inherited data from root_cause_stage.
        Any independent branches are excluded from the tainted set.
        """
        dag = self.position_matrices.get(trajectory_id, {})
        tainted: Set[int] = {root_cause_stage}
        changed = True

        while changed:
            changed = False
            for child, parents in dag.items():
                if child not in tainted and any(p in tainted for p in parents):
                    tainted.add(child)
                    changed = True

        return tainted

    def surgical_targeted_rollback(
        self,
        trajectory_id: str,
        root_cause_stage: int,
        corrected_output: str,
        corrected_evidence: Optional[List[str]] = None,
        agent_name: str = "TargetedRollbackAgent"
    ) -> AgentStageState:
        """
        Positional Matrix Surgical Rollback:
        1. Queries the Positional Dependency Matrix to identify tainted descendants.
        2. PRESERVES untainted independent stages (zero wasted recomputation).
        3. Wipes ONLY the tainted causal branch.
        4. Resets the abort event and injects the corrected premise.
        5. Re-engages asynchronous parallel verification.
        """
        tainted_stages = self.get_tainted_subgraph(trajectory_id, root_cause_stage)
        print(f"[*] SURGICAL ROLLBACK: Root Cause Step = {root_cause_stage}. Tainted Branch = {sorted(tainted_stages)}")

        # 1. Prune only tainted states from active history (preserve independent branches)
        if trajectory_id in self.active_trajectories:
            preserved_history = [s for s in self.active_trajectories[trajectory_id] if s.stage_id not in tainted_stages]
            self.active_trajectories[trajectory_id] = preserved_history
            preserved_ids = [s.stage_id for s in preserved_history]
            print(f"    [+] Preserved Clean Independent Stages: {preserved_ids}")

        # 2. Prune only tainted verification results
        if trajectory_id in self.verification_results:
            self.verification_results[trajectory_id] = {
                sid: res for sid, res in self.verification_results[trajectory_id].items()
                if sid not in tainted_stages
            }

        # 3. Clear abort event
        if trajectory_id in self.abort_events:
            self.abort_events[trajectory_id].clear()

        # 4. Inject corrected stage
        prior_state = [s for s in self.active_trajectories.get(trajectory_id, []) if s.stage_id < root_cause_stage]
        prior_context = prior_state[-1].stage_output if prior_state else "Cleaned System Root Context"

        corrected_state = self.capture_stage(
            trajectory_id=trajectory_id,
            stage_id=root_cause_stage,
            agent_name=agent_name,
            action_type="surgically_remediated_step",
            input_context=prior_context,
            stage_output=corrected_output,
            retrieved_evidence=corrected_evidence or [],
            parent_stage_ids=[s.stage_id for s in prior_state]
        )

        print(f"[+] SURGICAL RECOVERY COMPLETE: Corrected state injected at Step {root_cause_stage}. Independent branches preserved.")
        return corrected_state

    def capture_stage(
        self,
        trajectory_id: str,
        stage_id: int,
        agent_name: str,
        action_type: str,
        input_context: str,
        stage_output: str,
        retrieved_evidence: Optional[List[str]] = None,
        token_logprobs: Optional[List[float]] = None,
        confidence_score: Optional[float] = None,
        parent_stage_ids: Optional[List[int]] = None
    ) -> AgentStageState:
        """
        Non-blocking stage capture: persists state, registers dependency matrix, and feeds async worker.
        """
        # Default causal dependency: previous sequential stage if not specified
        parents = parent_stage_ids if parent_stage_ids is not None else ([stage_id - 1] if stage_id > 1 else [])
        self.register_causal_dependency(trajectory_id, stage_id, parents)

        state = AgentStageState(
            trajectory_id=trajectory_id,
            stage_id=stage_id,
            agent_name=agent_name,
            action_type=action_type,
            input_context=input_context,
            stage_output=stage_output,
            retrieved_evidence=retrieved_evidence or [],
            token_logprobs=token_logprobs,
            confidence_score=confidence_score,
            parent_stage_ids=parents,
            timestamp=time.time()
        )

        if trajectory_id not in self.active_trajectories:
            self.active_trajectories[trajectory_id] = []
            self.abort_events[trajectory_id] = threading.Event()

        self.active_trajectories[trajectory_id].append(state)
        self.state_queue.put(state)

        with open(self.log_file, "a", encoding="utf-8") as f:
            f.write(json.dumps(state.to_log_dict()) + "\n")

        print(f"[*] Interceptor: Captured Stage {stage_id} (Parents: {parents}) for Agent [{agent_name}] in Trajectory {trajectory_id[:8]} (Async Queued)")
        return state

    def get_trajectory_history(self, trajectory_id: str) -> List[AgentStageState]:
        """Returns the full sequence of stages recorded for a trajectory."""
        return self.active_trajectories.get(trajectory_id, [])

    def wrap_agent_step(self, agent_name: str, stage_id: int, original_func: Callable) -> Callable:
        """
        Decorator to monkey-patch AutoAgent execution functions with speculative abort checking.
        """
        def wrapper(trajectory_id: str, input_context: str, *args, **kwargs):
            if self.is_trajectory_aborted(trajectory_id):
                raise RuntimeError(f"Speculative Execution Aborted: Cascading Hallucination halted trajectory {trajectory_id[:8]}.")
            evidence = kwargs.get("evidence", [])
            output = original_func(input_context, *args, **kwargs)
            self.capture_stage(
                trajectory_id=trajectory_id,
                stage_id=stage_id,
                agent_name=agent_name,
                action_type="agent_step",
                input_context=input_context,
                stage_output=str(output),
                retrieved_evidence=evidence
            )
            return output
        return wrapper

interceptor = StateInterceptor()

if __name__ == "__main__":
    print("[-] Testing State Interceptor with Asynchronous Parallel Verification...")
    test_tid = "test-async-001"

    # Mock detector for testing async pipeline
    class MockDetector:
        def evaluate_stage(self, stage_id, current_output, prior_context, retrieved_evidence, confidence_score=None):
            time.sleep(0.05)  # Simulate 50ms DeBERTa cross-encoder work
            return {
                "stage_id": stage_id,
                "p_cascade": 0.82 if stage_id >= 2 and "hallucination" in current_output else 0.12,
                "cascade_flag": bool(stage_id >= 2 and "hallucination" in current_output),
                "mitigation_type": "CRR" if stage_id == 1 else "PVA"
            }

    interceptor.start_async_worker(MockDetector())

    t_start = time.time()
    s1 = interceptor.capture_stage(
        trajectory_id=test_tid,
        stage_id=1,
        agent_name="LocalFileAgent",
        action_type="document_retrieval",
        input_context="Query: Check corporate travel allowance.",
        stage_output="Retrieved Doc: Per diem is $75 per day.",
        retrieved_evidence=["Per diem is $75 per day."]
    )

    # Downstream agent runs immediately without blocking on DeBERTa!
    s2 = interceptor.capture_stage(
        trajectory_id=test_tid,
        stage_id=2,
        agent_name="OrchestratorAgent",
        action_type="reasoning_step",
        input_context=s1.stage_output,
        stage_output="Reasoning: Detected a critical hallucination claiming $750 allowance.",
        retrieved_evidence=s1.retrieved_evidence
    )
    dispatch_time_ms = (time.time() - t_start) * 1000.0
    print(f"    [+] Speculative Agent Hand-off Time: {dispatch_time_ms:.2f} ms (Perceived Latency: ~0 ms)")

    # Wait briefly for background worker to catch the error
    time.sleep(0.15)
    assert interceptor.is_trajectory_aborted(test_tid), "Async abort event should have fired!"
    print(f"    [+] Async Abort Token successfully caught cascade: {interceptor.is_trajectory_aborted(test_tid)}")

    interceptor.stop_async_worker()
    print("    [+] Phase 2 Asynchronous Parallelism fully verified.")

